defaults:
  start-y: 70
  height:
    editable: true
    min: 3
    max: 30
    default: 10
  distance-between-pillars:
    editable: true
    min: 10
    max: 50
    small: 12
    medium: 18
    large: 28
  material:
    editable: true
    default: BEDROCK
    filter:
      - "GOLD"
      - "DIAMOND"
      - "IRON"
      - "WOOD"
  itemtime:
    editable: true
    default: 30
    min: 5
    max: 60
  total-rounds:
    editable: true
    default: 10
    min: 3
    max: 30

drop-item:
  filter:
    - "_BLOCK"
    - "STICK"
    - "CHEST"

messages:
  game-starting: "Game starting."
  player-died: "%player% died."
  player-won: "%player% won this round."
  command:
    reloaded: "Config reloaded."
    console: "Only a player can do this."
    invalid-args: "Invalid arguments."

# If enabled, game master will be able to /voidgame troll <player>
# and it will give that player the same item the entire time
troll-mode:
  enabled: true
  material: "POISONOUS_POTATO"

# formatted as follows: sound,volume,pitch
sound:
  game-starting: ""
  you-died: "ANVIL_BREAK,0.5,1.0"
  other-died: ""
  next-round: ""
  countdown: ""
  item-drop: ""