defaults:
  start-y: 70
  height:
    min: 3
    max: 30
    default: 10
  distance-between-pillars:
    min: 10
    max: 50
    default: 18
  material:
    editable: true
    default: BEDROCK
    filter:
      - "GOLD"
      - "DIAMOND"
      - "IRON"
      - "WOOD"
  itemtime:
    default: 30
    min: 5
    max: 60
  total-rounds:
    default: 10
    min: 3
    max: 30

drop-item:
  filter:
    - "AIR"
    - "_BLOCK"
    - "STICK"
    - "CHEST"

messages:
  prefix: "&3&lVoid&6&lGame &r&c> &r"
  game-starting: "Game starting."
  player-died: "%player% died."
  player-won: "%player% won this round."
  not-found: ""
  command:
    reloaded: "Config reloaded."
    console: "Only a player can do this."
    invalid-args: "Invalid arguments."
    no-permission: "You don't have the permission to do that."

# In seconds
invitation-timeout: 30

# If enabled, game master will be able to /voidgame troll <player>
# and it will give that player the same item every time
troll:
  enabled: true
  material: "POISONOUS_POTATO"

# formatted as follows: sound,volume,pitch
sound:
  game-starting: ""
  you-died: "ANVIL_BREAK,0.5,1.0"
  other-died: ""
  next-round: ""
  countdown: ""
  item-drop: ""