pillar:
  start-y: 70
  height: 10
  material: "BEDROCK"

distance-between-pillars:
  small: 12
  medium: 18
  large: 28

messages:
  game-starting: "Game starting."
  player-died: "%player% died."
  player-won: "%player% won this round."
  command:
    reloaded: "Config reloaded."
    console: "Only a player can do this."
    invalid-args: "Invalid arguments."

# If enabled, game master will be able to /voidgame troll <player>
# and it will give that player the same item the entire time
troll-mode:
  enabled: true
  material: "POISONOUS_POTATO"

# formatted as follows: sound,volume,pitch
sound:
  game-starting: ""
  you-died: "ANVIL_BREAK,0.5,1.0"
  other-died: ""
  next-round: ""
  countdown: ""
  item-drop: ""