name: VoidGame
version: '${project.version}'
main: com.github.justadeni.voidgame.VoidGame
api-version: '1.20'
commands:
  voidgame:
    aliases: [vg]
    description: used for interacting with VoidGame arenas